name: first workflow automation
on:
  push:
    branches: ["master"]

  
  pull_request:
    branches: ["master"]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: checking out the repository
        uses: actions/checkout@v3

      - name: setting python environment
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'
          cache: 'pip'

      - name: Installing dependencies
        run: |
              python3 -m pip install -r .github/workflows/requirements.txt

      - name :  running script 
        env:
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}} 
          USER_ID: ${{secrets.FITZ_ID}}
          GITHUB_REPOSITORY: ${{github.repository}}
          GITHUB_EVENT_AUTHOR: ${{github.event.pusher.username}}
        run: |
              python3 .github/workflows/source/index.py
