name: first workflow automation
on:
  push:
    branches: ["master"]

  
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checking out the repository
        uses: actions/checkout@v3

      - name: setting python environment
        uses: actions/setup-python@v5
        with: 
          python-version: '3.10'

      - name :  running script 
        run: |
              ls
              python3 .github/workflows/source/index.py
